source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpiriaKeyboardAdjustment_Example', :exclusive => true do
  pod 'SpiriaKeyboardAdjustment', :path => '../'
end

target 'SpiriaKeyboardAdjustment_Tests', :exclusive => true do
  pod 'SpiriaKeyboardAdjustment', :path => '../'

  
end
